### ISSUE TITLE
Problamas para medir el tiempo

### ISSUE THREAD

**Issue by manurua123** [manurua123/Python2020-FINAL#2]
Sigo con problemas para poder medir el tiempo mientras trancurre el turno. Intente de varias formas, pero no logro crear algun timpo de cronometro, puedo calcular el tiempo entre dos momentos pero no logro que sea algo automatico, que todo el tiempo este chequeando el tiempo para ver si sigue siendo el turno de la persona.

**Comment by tomibarbieri** [comment]
Manu, como estas, les mando por mail en un ratito una idea para resolver el reloj y el tema de la inteligencia.

**Comment by manurua123** [comment]
Buenas, había llegado a una solución similar para el tema del tiempo usando un ejemplo que está en el git de PySimpleGUI, pero igual sigue sin fusionar, se cuál es el problema, pero no se me ocurre como resolverlo. 

Para saber cuándo es el turno del jugador y cuando el de la maquina uso una variable auxiliar llamada turno, cuando el jugador pasa, la palabra que ingresa es correcta o se acaba el tiempo la variable pasa a False e inicia el turno de la máquina que ya lo tengo casi todo resuelto. 
El problema está en que es que el contador de tiempo solo funciona si está dentro del loop principal, una vez que entra al while o al if del turno deja de contar, solo aumenta cuando se realiza una acción (tocar un botón del atril o del tablero)

Es medio complicado de explicarlo por acá, el jueves te comparto pantalla y te muestro cuales son los problemas con los que me estoy encontrando.

**Comment by tomibarbieri** [comment]
Bueno dale, lo vemos el jueves. Pero cualquier cosa si lo llego a probar antes te aviso.

**Comment by manurua123** [comment]
Listo, ya esta soluciondo. Gracias.
