### ISSUE TITLE
Que pasa si la PC no puede crear una palabra?

### ISSUE THREAD

**Issue by manurua123** [manurua123/Python2020-FINAL#4]
Hola.

Me falta ponerme a acomodar un poco el código, pero ya terminé con todas las funcionalidades, la ia funciona, se puede guardar y cargar una partida, los multiplicadores funciona, etc., pero ahora me surge un problema o más bien una duda.  Estuve probando el juego un par de partidas y siempre llega un punto en que la maquina no puede generar más palabras, normalmente pone dos o tres palabras y se le llena el atril de consonantes, también me pasa como jugador, pero tengo la opción de cambiar las letras un par de veces por partida.  

Lo dejo así  o implemento algún método para que si no puede generar una palabra puede devolver la mano como hace el jugador. La consigna dice que lo deje asi, pero el juego se traba mucho, siempre terminas juegando solo.

**Comment by tomibarbieri** [comment]
Hola Manu, como estas?

Que bueno que ya estes bastante avanzado. Vayamos viendo, si llegas al final antes, dejamos todo listo antes de la entrega final asi no tenes que preocuparte mas (dsp tendriamos la defensa formal, pero vos ya te quedas tranquilo que esta todo bien).

En cuanto a eso, no es necesario que avances en esa funcionalidad, si la maquina no tiene mano para jugar, dsp de algunos intentos o algún tiempo, que pase la jugada.

Este jueves no hay clases, pero coordinamos algun encuentro de ser necesario. Voy a mandar un mail general.

Abrazo
Tom
